version: "3.8"

services:
  portfolio:
    build: .
    container_name: portfolio-app
    expose:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - portfolio_network

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - portfolio
    restart: unless-stopped
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge
